services:
  traefik:
    container_name: typephoon-traefik
    image: traefik:latest
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - FRONTEND_HOST=host.docker.internal:3000
      - BACKEND_HOST=host.docker.internal:8080
    volumes:
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yml
      - ./traefik/dynamic.yaml:/etc/traefik/dynamic.yml
