log:
  level: INFO

entryPoints:
  web:
   address: ":9090"

providers:
  file:
    filename: "/etc/traefik/traefik.yml"

http:
  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://192.168.70.223:3000"

    backend:
      loadBalancer:
        servers:
          - url: "http://192.168.70.223:8080"

    backend_ws:
      loadBalancer:
        servers:
          - url: "ws://192.168.70.223:8080"

  routers:
    frontend:
      rule: "PathPrefix(`/`)"
      service: "frontend"

    backend:
      rule: "PathPrefix(`/api/v1`)"
      service: "backend"

    backend_lobby_ws:
      rule: "PathPrefix(`/api/v1/lobby/queue-in/ws`)" 
      service: "backend_ws"

    backend_game_ws:
      rule: "PathPrefix(`/api/v1/game/ws`)" 
      service: "backend_ws"
